import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Navbar from "@/app/components/navbar";
import dynamic from "next/dynamic";
import { Banner } from "@/app/components/Banner";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const WalletConnectionProvider = dynamic(
  () => import("./WalletConnectionProvider"),
  {
    ssr: false,
  }
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <UserProvider>
        <html lang="en">
          <body className={inter.className}>
            <Navbar />
            <Banner />
            <WalletConnectionProvider>{children}</WalletConnectionProvider>
          </body>
        </html>
      </UserProvider>
    </>
  );
}
